x-common-logging: &common-logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "5"

x-common-restart-policy: &common-restart-policy
  restart: unless-stopped

services:
  app:
    image: svhd/logto:${LOGTO_TAG}
    <<: *common-restart-policy
    entrypoint: ["/bin/sh", "/usr/local/bin/init.sh"]
    env_file:
      - .env
    ports:
      - "127.0.0.1:${LOGTO_PORT_CORE}:3001"
      - "127.0.0.1:${LOGTO_PORT_ADMIN}:3002"
    volumes:
      - ./init.sh:/usr/local/bin/init.sh
    networks:
      - logto-net
    logging: *common-logging
    depends_on:
      db:
        condition: service_healthy
    environment:
      - TRUST_PROXY_HEADER=1
      - DB_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}
      - ENDPOINT=${ENDPOINT}
      - ADMIN_ENDPOINT=${ADMIN_ENDPOINT}

  db:
    image: postgres:17-alpine
    <<: *common-restart-policy
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      # Important: PGDATA must point to a subdir of the mount point
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/pgdata
    ports:
      - "127.0.0.1:${DB_PORT}:${DB_PORT}"
    # Force Postgres to listen on the configured port
    command: -p ${DB_PORT}
    networks:
      - logto-net
    logging: *common-logging
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} -p ${DB_PORT}"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  logto-net:
    driver: bridge